### ISSUE TITLE
XHTML declaring itself text/html

### ISSUE THREAD

**Issue by wking** [spdx/tools#123]
Spun off from [here][1].  We're serving the license pages as HTML:

```console
$ curl -sI https://spdx.org/licenses/preview/ISC.html | grep Content-Type
Content-Type: text/html; charset=UTF-8
```

and doubling down on that with [a `meta http-equiv` in the template][2] (and a few sibling templates under `htmlTemplate`.  This conflicts with the [W3C recommendation][3] that XHTML served as text/html [not contain XML declarations][4] (which our templates [do][5]).  I see two potential solutions:

a. Serve our XHTML as [application/xhtml+xml][6].  This works for clients that ask for XHTML, but the W3C recommends only serving it to clients who “[*explicitly* indicate they support this media type][7]”, so we'd need HTML versions to serve to everyone else.
b. Drop XHTML and just serve vanilla HTML5.

(a) is a superset of (b), since we'll need a vanilla HTML option to comply with the W3C recommendations for clients who don't explicitly indicate they support XHTML.  The question is whether we want to continue to support XHTML in parallel or not.  With XML data already available from license-list-XML, I don't see a point to continuing to maintain XHTML output.  If that seems like a reasonable position, I can start filing PRs to transition the templates to HTML5.

[1]: https://github.com/spdx/tools/pull/122#issuecomment-348309372
[2]: https://github.com/spdx/tools/blob/d8ef31bf86099dd700555e9d173719a6478b2c46/resources/htmlTemplate/LicenseHTMLTemplate.html#L12
[3]: https://www.w3.org/TR/2009/NOTE-xhtml-media-types-20090116/#text-html
[4]: https://www.w3.org/TR/2009/NOTE-xhtml-media-types-20090116/#C_1
[5]: https://github.com/spdx/tools/blob/d8ef31bf86099dd700555e9d173719a6478b2c46/resources/htmlTemplate/LicenseHTMLTemplate.html#L1
[6]: https://tools.ietf.org/html/rfc3236
[7]: https://www.w3.org/TR/2009/NOTE-xhtml-media-types-20090116/#application-xhtml-xml

**Comment by goneall** [comment]
> The question is whether we want to continue to support XHTML in parallel or not. 

To be honest, I'm not sure why we are using XML.  I picked up support for this from someone much more knowledgeable than myself on HTML.  He implemented RDFa and I believe added the XML.  I thought the XML was required for RDFa, but doing a quick web search seems to indicate XHTML is supported but not required (see https://www.w3.org/TR/html-rdfa/).

If it turns out RDFa requires XML, we probably need to keep it for compatibility.

The RDFa was introduced years ago (before my time) and I know of a few instances where it is still in use including the SPDX tools.  If we were to start over, I would prefer to move to JSON as it is much cleaner than the embedded RDFa, but we would have a migration of unknown impact.

If we can do (b) and support RDFa, I would vote for that option.

**Comment by goneall** [comment]
moved to https://github.com/spdx/LicenseListPublisher/issues/16
