### ISSUE TITLE
Deprecated license identifiers in JSON file

### ISSUE THREAD

**Issue by kemitchell** [spdx/tools#73]
I notice that the identifiers listed under "Deprecated Licenses" in the [license list](https://spdx.org/licenses/) are not included in the JSON list at https://spdx.org/licenses/licenses.json. Is this intentional?

Most troubling are eCos-2.0 and WxWindows, which are OSI-approved.

**Comment by goneall** [comment]
I don't think it was intentional - the RDF version of the license list includes the deprecated licenses.

I'll add this in to the tool so they will be included in the next license list update which should be sometime around the first week of January.

BTW - The eCos-2.0 license was replaced by (GPL-2.0 with eCos-exception-2.0) and the WxWindows license was replaced by (GPL-2.0 with WxWindows-exception-3.1)

**Comment by kemitchell** [comment]
@goneall Thanks for this!

Frankly, if there are approved equivalents, I'm not sure the JSON list should include the old deprecated identifiers. At a minimum, it might be nice to list licenses with a boolean deprecated flag, like `isOSIApproved`.

**Comment by goneall** [comment]
Good point.  Turns out there is no deprecated flag for the RDFa format either.  I would like to keep the two formats in sync.

In the short term, we could not include the deprecated licenses in the JSON format (as it is today) and fix the application to not include them in the RDFa format either to keep both formats in sync.

Longer term, we could add a deprecated flag - since this is a change to the spec we would need agreement from the spdx-tech group.

**Comment by kemitchell** [comment]
Is "deprecated" defined or otherwise discussed in the spec?

I assume the concept was introduced more from a technical point of view than a legal one. Compare OSI, which doesn't "deprecate", but does categorize.

https://opensource.org/licenses/category

Both "superseded" and "retired" are OSI categories.

**Comment by goneall** [comment]
I believe the only references to the deprecated licenses are on the spdx.org/licenses web page itself.  I do believe it was a technical consideration that drove this definition.  There was a proposal to remove the license ID's since they were no longer needed due to the license expression syntax introduced in SPDX 2.0.

The technical team was concerned that SPDX 1.0 applications would break if these were removed completely, so we came up with the deprecated approach.

**Comment by goneall** [comment]
@kemitchell I'm about to start working on the license list tool to add detailed JSON pages for each license.  What if I add another Boolean field for each license entry in the licenses.json file "deprecated" which would be true if the license is deprecated?  This would make it easier to filter.  

Would this break anything?  Seems like it should be backwards compatible for must usage.

**Comment by kemitchell** [comment]
That sounds great.

**Comment by goneall** [comment]
Going back through the old issues - I see that this has been updated on spdx.org/licenses.  The deprecated licenses are now include with a flag deprecated=true.
