### ISSUE TITLE
No way to obtain packages not related to document

### ISSUE THREAD

**Issue by yevster** [spdx/tools#83]
There is no way to list all the packages in the document. So in a scenario where Document describes Package 1 and Package 1 is related to Package 2, there is no way to get to Package 2 without a depth-first search through all the relationships.

This can be counterproductive when trying to manipulate the document, given that with the addition of filesAnalyzed in 2.1, a document will now contain many packages.

**Comment by goneall** [comment]
Correct - for files and snippets there are some convenience methods in SpdxDocumentContainer findAllFiles and fileAllSnippets.  I'll add another method findAllPackages since I'm looking around in that code right now anyway.  It won't be the highest performing function, but it will probably be good enough for most sized documents.

**Comment by goneall** [comment]
Update - It looks like findAllPackages was already implemented (I missed on on a first pass).  On the SpdxDocumentContainer - just call findAllPackages and it will return all packages in the document.  A bit slow - I can think of some ways of improving performance if it turns out to be a problem.

Let me know if this resolves the issue.

**Comment by yevster** [comment]
It does provide the functionality! I already implemented my own method for doing this, but this seems to work the same. Using `model.listResourcesWithProperty(...)` might simplify the code a bit, perhaps.
